name: EnVolte
description: O melhor professor é aquele que te faz aprender ;)
meta_description: "Um blog para te ajudar com coisas sobre blogs e sites ;)"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 2
baseurl: 'http://envolte.github.io/'
domain_name: 'http://envolte.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate-v2]
 
pagination:
  enabled: true
  per_page: 2
  permalink: '/pagina/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  cursos:
    output: true
    permalink: /curso/:name

defaults:
  - scope:
      path: "_cursos"
      type: "curso"
    values:
      layout: post

# Details for the RSS feed generator
url:            'http://envolte.github.io'
author:         'Luís Fernando'
