name: EnVolte
description: O melhor professor é aquele que te faz aprender de verdade ;)
meta_description: "Um blog para te ajudar com coisas sobre blogs e sites ;)"

markdown: kramdown
highlighter: pygments
logo: true
baseurl: 'http://envolte.github.io/'
domain_name: 'http://envolte.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: ["jekyll-paginate", "jekyll-related-posts"]
paginate: 4
permalink: /:categories/:year/:title.envolte
cursophp: 'https://envolte.github.io/assets/images/capaphp.png'
cursohtmlcss: 'https://envolte.github.io/assets/images/capahtmlcss.png'

related:
  max_count: 5

plugins:
- jekyll-paginate-v2
  
collections:
  cursos:
    output: true
    permalink: /curso/:path

defaults:
  - scope:
      path: "/cursos/"
      type: "curso"
    values:
      layout: curso
      language: man


# Details for the RSS feed generator
url:            'http://envolte.github.io'
author:         'Luís Fernando'
